--- a/.github/workflows/github-ci-clang.yml
+++ b/.github/workflows/github-ci-clang.yml
@@ -79,4 +79,4 @@
       run: |
         python3 scripts/unittest.py
 
-# vim: ts=2 sw=2 expandtab
+# vim: ts=2 sw=2 expandtab